"""Type stubs for rocksgraph — enables IDE autocompletion and suppresses Pylance warnings."""
from __future__ import annotations
from typing import Any, Optional, List, Set, Dict, Union
from enum import Enum, IntEnum

class StoreError(Exception):
    """Base exception for all RocksGraph storage/query errors. Never raised
    directly — always one of its subclasses below."""

class StorageError(StoreError):
    """The storage engine itself is unhealthy (RocksDB failure, I/O error,
    corrupt data, misconfiguration). Not retryable."""

class TransactionError(StoreError):
    """A transaction could not proceed due to concurrent access (OCC
    conflict, lock error) or an in-progress bulk load."""

class SchemaError(StoreError):
    """A schema declaration or strictness rule was violated, conflicted, or
    exhausted its ID space."""

class IntegrityError(StoreError):
    """A data integrity constraint was violated: missing key, duplicate
    vertex/edge, dropping a vertex with incident edges, or writing to a
    read-only snapshot."""

class VectorError(StoreError):
    """A vector index operation failed (dimension mismatch, capacity, I/O, etc.)."""

class QueryError(StoreError):
    """The query itself is invalid: unsupported construct, type mismatch, or
    malformed traversal."""

class T:
    id: str
    label: str
    key: str
    value: str

class Direction(Enum):
    OUT = "out"
    IN = "in"
    BOTH = None

class Order(Enum):
    asc = "asc"
    desc = "desc"

class DataType(IntEnum):
    Null = 0
    Bool = 1
    Int32 = 2
    Int64 = 3
    Float32 = 4
    Float64 = 5
    String = 6
    Uuid = 7
    UInt16 = 8
    Bytes = 9
    FloatVector = 10

class SchemaMode(str, Enum):
    Auto = "auto"
    Strict = "strict"

class EdgeMode(str, Enum):
    Single = "single"
    Multi = "multi"

class VectorEntityType(str, Enum):
    Vertex = "vertex"
    Edge = "edge"

class DistanceMetric(str, Enum):
    Cosine = "cosine"
    Euclidean = "euclidean"
    L2 = "l2"
    DotProduct = "dot_product"

class AnnAlgorithm(str, Enum):
    BruteForce = "brute_force"
    Hnsw = "hnsw"

class Quantization(str, Enum):
    F16 = "f16"
    F32 = "f32"

class VectorIndexConfig:
    property: str
    dimension: int
    entity_type: str
    metric: str
    algorithm: str
    m: int
    ef_construction: int
    ef_search: int
    quantization: str
    def __init__(
        self,
        property: str,
        dimension: int,
        *,
        entity_type: Union[str, VectorEntityType] = VectorEntityType.Vertex,
        metric: Union[str, DistanceMetric] = DistanceMetric.Cosine,
        algorithm: Union[str, AnnAlgorithm] = AnnAlgorithm.Hnsw,
        m: int = 16,
        ef_construction: int = 200,
        ef_search: int = 50,
        quantization: Union[str, Quantization] = Quantization.F16,
    ) -> None: ...

class BulkVertex:
    id: int
    label: str
    props: dict
    def __init__(self, id: int, label: str, props: Optional[dict] = None) -> None: ...

class BulkEdge:
    src: int
    dst: int
    label: str
    props: dict
    rank: Optional[int]
    def __init__(self, src: int, dst: int, label: str, props: Optional[dict] = None, rank: Optional[int] = None) -> None: ...

class BulkLoadStats:
    vertices_written: int
    edges_written: int
    sst_files: int
    duration_secs: float
    def __init__(self, vertices_written: int, edges_written: int, sst_files: int, duration_secs: float) -> None: ...

class RocksOptions:
    block_cache_size: int
    write_buffer_size: int
    max_write_buffer_number: int
    max_background_jobs: int
    vertex_block_size: int
    edge_block_size: int
    cache_index_and_filter_blocks: bool
    def __init__(
        self,
        *,
        block_cache_size: int = 1024 * 1024 * 1024,
        write_buffer_size: int = 64 * 1024 * 1024,
        max_write_buffer_number: int = 3,
        max_background_jobs: int = 2,
        vertex_block_size: int = 4096,
        edge_block_size: int = 4096,
        cache_index_and_filter_blocks: bool = True,
    ) -> None: ...

class IndexOptions:
    default_memory_limit: int
    per_index_overrides: list
    def __init__(
        self,
        *,
        default_memory_limit: int = 0,
        per_index_overrides: Optional[list] = None,
    ) -> None: ...

class GraphOptions:
    mode: Union[str, SchemaMode]
    edge_mode: Union[str, EdgeMode]
    storage: RocksOptions
    index: IndexOptions
    def __init__(
        self,
        *,
        mode: Union[str, SchemaMode] = "auto",
        edge_mode: Union[str, EdgeMode] = "single",
        storage: Optional[RocksOptions] = None,
        index: Optional[IndexOptions] = None,
    ) -> None: ...

class P:
    tag: int
    value: Any
    def __init__(self, tag: int, value: Any) -> None: ...
    def __iter__(self): ...
    @staticmethod
    def eq(value: Any) -> P: ...
    @staticmethod
    def neq(value: Any) -> P: ...
    @staticmethod
    def gt(value: Any) -> P: ...
    @staticmethod
    def gte(value: Any) -> P: ...
    @staticmethod
    def lt(value: Any) -> P: ...
    @staticmethod
    def lte(value: Any) -> P: ...
    @staticmethod
    def between(v1: Any, v2: Any) -> P: ...
    @staticmethod
    def within(*values: Any) -> P: ...
    @staticmethod
    def without(*values: Any) -> P: ...

class __:
    @staticmethod
    def V(*ids: int) -> Traversal: ...
    @staticmethod
    def out(*labels: str) -> Traversal: ...
    @staticmethod
    def in_(*labels: str) -> Traversal: ...
    @staticmethod
    def both(*labels: str) -> Traversal: ...
    @staticmethod
    def outE(*labels: str) -> Traversal: ...
    @staticmethod
    def inE(*labels: str) -> Traversal: ...
    @staticmethod
    def bothE(*labels: str) -> Traversal: ...
    @staticmethod
    def outV() -> Traversal: ...
    @staticmethod
    def inV() -> Traversal: ...
    @staticmethod
    def otherV() -> Traversal: ...
    @staticmethod
    def has(*args: Any) -> Traversal: ...
    @staticmethod
    def hasLabel(*labels: str) -> Traversal: ...
    @staticmethod
    def values(*keys: str) -> Traversal: ...
    @staticmethod
    def properties(*keys: str) -> Traversal: ...
    @staticmethod
    def id() -> Traversal: ...
    @staticmethod
    def label() -> Traversal: ...
    @staticmethod
    def identity() -> Traversal: ...
    @staticmethod
    def constant(value: Any) -> Traversal: ...
    @staticmethod
    def limit(limit: int) -> Traversal: ...
    @staticmethod
    def count() -> Traversal: ...
    @staticmethod
    def dedup() -> Traversal: ...
    @staticmethod
    def degree(direction: Optional[str] = None) -> Traversal: ...
    @staticmethod
    def fold() -> Traversal: ...
    @staticmethod
    def unfold() -> Traversal: ...
    @staticmethod
    def sum() -> Traversal: ...
    @staticmethod
    def max() -> Traversal: ...
    @staticmethod
    def min() -> Traversal: ...
    @staticmethod
    def mean() -> Traversal: ...
    @staticmethod
    def group() -> Traversal: ...
    @staticmethod
    def groupCount() -> Traversal: ...
    @staticmethod
    def path() -> Traversal: ...
    @staticmethod
    def simplePath() -> Traversal: ...
    @staticmethod
    def cyclicPath() -> Traversal: ...
    @staticmethod
    def as_(*labels: str) -> Traversal: ...
    @staticmethod
    def select(*labels: str) -> Traversal: ...
    @staticmethod
    def coalesce(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def union(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def and_(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def or_(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def not_(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def where(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def local(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def choose(predicate_t: Traversal, true_t: Traversal, false_t: Optional[Traversal] = None) -> Traversal: ...
    @staticmethod
    def repeat(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def addV(label: str, vid: Optional[int] = None) -> Traversal: ...
    @staticmethod
    def addE(label: str) -> Traversal: ...
    @staticmethod
    def from_(v: Any) -> Traversal: ...
    @staticmethod
    def to(v: Any) -> Traversal: ...
    @staticmethod
    def property(key: str, value: Any) -> Traversal: ...
    @staticmethod
    def nearest(property: str, query: Any, k: int) -> Traversal: ...
    @staticmethod
    def similarity(property: str, query: Any) -> Traversal: ...
    @staticmethod
    def hasId(value: Any) -> Traversal: ...
    @staticmethod
    def drop() -> Traversal: ...

class Traversal:
    steps: list  # internal: list of (opcode, args) tuples
    session: Any  # internal: ReadSession or TxSession or None

    def __init__(self, session: Any = None, steps: Optional[list] = None) -> None: ...
    def V(self, *ids: int) -> Traversal: ...
    def E(self, *keys: str) -> Traversal: ...
    def addV(self, label: str, vid: Optional[int] = None) -> Traversal: ...
    def addE(self, label: str) -> Traversal: ...
    def from_(self, v: Any) -> Traversal: ...
    def to(self, v: Any) -> Traversal: ...
    def property(self, key: str, value: Any) -> Traversal: ...
    def withProperties(self, *keys: str) -> Traversal: ...
    def out(self, *labels: str) -> Traversal: ...
    def in_(self, *labels: str) -> Traversal: ...
    def both(self, *labels: str) -> Traversal: ...
    def outE(self, *labels: str) -> Traversal: ...
    def inE(self, *labels: str) -> Traversal: ...
    def bothE(self, *labels: str) -> Traversal: ...
    def outV() -> Traversal: ...
    def inV() -> Traversal: ...
    def otherV() -> Traversal: ...
    def has(self, *args: Any) -> Traversal: ...
    def hasLabel(self, *labels: str) -> Traversal: ...
    def hasId(self, value: Any) -> Traversal: ...
    def hasRank(self, value: Any) -> Traversal: ...
    def values(self, *keys: str) -> Traversal: ...
    def properties(self, *keys: str) -> Traversal: ...
    def nearest(self, property: str, query: Any, k: int) -> Traversal: ...
    def with_ef_search(self, ef: int) -> Traversal: ...
    def similarity(self, property: str, query: Any) -> Traversal: ...
    def id(self) -> Traversal: ...
    def label(self) -> Traversal: ...
    def rank(self) -> Traversal: ...
    def identity(self) -> Traversal: ...
    def constant(self, value: Any) -> Traversal: ...
    def limit(self, limit: int) -> Traversal: ...
    def range(self, lo: int, hi: int) -> Traversal: ...
    def skip(self, n: int) -> Traversal: ...
    def tail(self, n: int) -> Traversal: ...
    def count(self) -> Traversal: ...
    def dedup(self) -> Traversal: ...
    def degree(self, direction: Optional[str] = None) -> Traversal: ...
    def fold(self) -> Traversal: ...
    def unfold(self) -> Traversal: ...
    def sum(self) -> Traversal: ...
    def max(self) -> Traversal: ...
    def min(self) -> Traversal: ...
    def mean(self) -> Traversal: ...
    def group(self) -> Traversal: ...
    def groupCount(self) -> Traversal: ...
    def order(self) -> Traversal: ...
    def by(self, key_spec: Any, order: str = "asc") -> Traversal: ...
    def path(self) -> Traversal: ...
    def simplePath(self) -> Traversal: ...
    def cyclicPath(self) -> Traversal: ...
    def as_(self, *labels: str) -> Traversal: ...
    def select(self, *labels: str) -> Traversal: ...
    def coalesce(self, *traversals: Traversal) -> Traversal: ...
    def union(self, *traversals: Traversal) -> Traversal: ...
    def and_(self, *traversals: Traversal) -> Traversal: ...
    def or_(self, *traversals: Traversal) -> Traversal: ...
    def not_(self, traversal: Traversal) -> Traversal: ...
    def where(self, traversal: Traversal) -> Traversal: ...
    def local(self, traversal: Traversal) -> Traversal: ...
    def choose(self, predicate_t: Traversal, true_t: Traversal, false_t: Optional[Traversal] = None) -> Traversal: ...
    def repeat(self, traversal: Traversal) -> Traversal: ...
    def until(self, traversal: Traversal) -> Traversal: ...
    def times(self, n: int) -> Traversal: ...
    def emit(self, traversal: Optional[Traversal] = None) -> Traversal: ...
    def drop(self) -> Traversal: ...
    def next(self) -> Any: ...
    def to_list(self) -> list: ...
    def toList(self) -> list: ...
    def to_set(self) -> Set: ...
    def toSet(self) -> Set: ...
    def iterate(self) -> None: ...
    def explain(self) -> str: ...

class GraphTraversal(Traversal): ...

class IndexManager:
    """Handle for vector index maintenance operations (rebuild, save, future export/import)."""
    def rebuild(self, entity_type: Union[str, VectorEntityType], property: str) -> None: ...
    def save(self, entity_type: Union[str, VectorEntityType], property: str) -> None: ...
    def save_all(self) -> None: ...

class Graph:
    def __init__(self, path: str, *, options: Optional[GraphOptions] = None) -> None: ...
    @staticmethod
    def open_with_options(path: str, *, options: Optional[GraphOptions] = None) -> Graph: ...
    def read(self) -> ReadSession: ...
    def begin(self) -> TxSession: ...
    def open_schema(self) -> SchemaSession: ...
    def open_bulk_loader(self) -> BulkLoader: ...
    def index_manager(self) -> IndexManager: ...
    def close(self) -> None: ...

class SchemaSession:
    def add_vertex_label(self, name: str) -> SchemaSession: ...
    def add_edge_label(self, name: str) -> SchemaSession: ...
    def add_property_key(self, name: str, data_type: Union[int, DataType]) -> SchemaSession: ...
    def set_edge_mode(self, mode: Union[str, EdgeMode]) -> SchemaSession: ...
    def set_schema_mode(self, mode: Union[str, SchemaMode]) -> SchemaSession: ...
    def add_vector_index(
        self,
        config: Optional[VectorIndexConfig] = None,
        *,
        entity_type: Union[str, VectorEntityType] = VectorEntityType.Vertex,
        property: Optional[str] = None,
        dimension: Optional[int] = None,
        metric: Union[str, DistanceMetric] = DistanceMetric.Cosine,
        algorithm: Union[str, AnnAlgorithm] = AnnAlgorithm.Hnsw,
        m: int = 16,
        ef_construction: int = 200,
        ef_search: int = 50,
        quantization: Union[str, Quantization] = Quantization.F16,
    ) -> SchemaSession: ...
    def drop_vector_index(self, entity_type: Union[str, VectorEntityType], property: str) -> SchemaSession: ...
    def commit(self) -> None: ...
    def __enter__(self) -> SchemaSession: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class BulkLoader:
    def with_work_dir(self, path: str) -> BulkLoader: ...
    def with_max_sst_size(self, bytes: int) -> BulkLoader: ...
    def with_max_memory(self, bytes: int) -> BulkLoader: ...
    def load_vertices(self, vertices: List[Union[BulkVertex, dict]]) -> BulkLoader: ...
    def load_edges(self, edges: List[Union[BulkEdge, dict]]) -> BulkLoader: ...
    def commit(self) -> BulkLoadStats: ...
    def __enter__(self) -> BulkLoader: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class ReadSession:
    def g(self) -> GraphTraversal: ...
    def close(self) -> None: ...
    def __enter__(self) -> ReadSession: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class TxSession:
    def g(self) -> GraphTraversal: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> TxSession: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class Vertex:
    def __init__(self, d: dict) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self): ...
    @property
    def id(self) -> int: ...
    @property
    def label(self) -> str: ...
    @property
    def properties(self) -> dict: ...

class Edge:
    def __init__(self, d: dict) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self): ...
    @property
    def src(self) -> int: ...
    @property
    def dst(self) -> int: ...
    @property
    def label(self) -> str: ...
    @property
    def rank(self) -> int: ...
    @property
    def properties(self) -> dict: ...

class Property:
    def __init__(self, d: dict) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __repr__(self) -> str: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> Any: ...

class Int32:
    value: int
    def __init__(self, value: int) -> None: ...

class Int64:
    value: int
    def __init__(self, value: int) -> None: ...

class UInt16:
    value: int
    def __init__(self, value: int) -> None: ...

class Float32:
    value: float
    def __init__(self, value: float) -> None: ...

class Float64:
    value: float
    def __init__(self, value: float) -> None: ...

class Uuid:
    value: str
    def __init__(self, value: str) -> None: ...

class Vector:
    values: List[float]
    def __init__(self, values: Any) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def tolist(self) -> List[float]: ...
    def numpy(self) -> Any: ...
