from enum import Enum, IntEnum
from types import TracebackType
from typing import Any

from typing_extensions import Self

class StoreError(Exception): ...
class StorageError(StoreError): ...
class TransactionError(StoreError): ...
class SchemaError(StoreError): ...
class IntegrityError(StoreError): ...
class VectorError(StoreError): ...
class QueryError(StoreError): ...

class T:
    id: str
    label: str
    key: str
    value: str

class Direction(str, Enum):
    OUT = "out"
    IN = "in"
    BOTH = "both"
    Out: Direction
    In: Direction
    Both: Direction

class Order(str, Enum):
    Asc = "asc"
    Desc = "desc"
    asc: Order
    desc: Order

asc: Order
desc: Order

class DataType(IntEnum):
    Null = 0
    Bool = 1
    Int32 = 2
    Int64 = 3
    Float32 = 4
    Float64 = 5
    String = 6
    Uuid = 7
    UInt16 = 8
    Bytes = 9
    FloatVector = 10

class SchemaMode(str, Enum):
    Auto = "auto"
    Strict = "strict"

class EdgeMode(str, Enum):
    Single = "single"
    Multi = "multi"

class VectorEntityType(str, Enum):
    Vertex = "vertex"
    Edge = "edge"

class DistanceMetric(str, Enum):
    Cosine = "cosine"
    Euclidean = "euclidean"
    L2 = "l2"
    DotProduct = "dot_product"

class AnnAlgorithm(str, Enum):
    BruteForce = "brute_force"
    Hnsw = "hnsw"

class Quantization(str, Enum):
    F16 = "f16"
    F32 = "f32"

class VectorIndexConfig:
    property: str
    dimension: int
    entity_type: str
    metric: str
    algorithm: str
    m: int
    ef_construction: int
    ef_search: int
    quantization: str
    def __init__(
        self,
        property: str,
        dimension: int,
        *,
        entity_type: str | VectorEntityType = ...,
        metric: str | DistanceMetric = ...,
        algorithm: str | AnnAlgorithm = ...,
        m: int = 16,
        ef_construction: int = 200,
        ef_search: int = 50,
        quantization: str | Quantization = ...,
    ) -> None: ...

class BulkVertex:
    id: int
    label: str
    props: dict
    def __init__(self, id: int, label: str, props: dict | None = None) -> None: ...

class BulkEdge:
    src: int
    dst: int
    label: str
    props: dict
    rank: int | None
    def __init__(self, src: int, dst: int, label: str, props: dict | None = None, rank: int | None = None) -> None: ...

class BulkLoadStats:
    vertices_written: int
    edges_written: int
    sst_files: int
    duration_secs: float
    def __init__(self, vertices_written: int, edges_written: int, sst_files: int, duration_secs: float) -> None: ...

class RocksOptions:
    block_cache_size: int
    write_buffer_size: int
    max_write_buffer_number: int
    max_background_jobs: int
    vertex_block_size: int
    edge_block_size: int
    cache_index_and_filter_blocks: bool
    def __init__(
        self,
        *,
        block_cache_size: int = ...,
        write_buffer_size: int = ...,
        max_write_buffer_number: int = 3,
        max_background_jobs: int = 2,
        vertex_block_size: int = 4096,
        edge_block_size: int = 4096,
        cache_index_and_filter_blocks: bool = True,
    ) -> None: ...

class IndexOptions:
    default_memory_limit: int
    per_index_overrides: list
    def __init__(
        self,
        *,
        default_memory_limit: int = 0,
        per_index_overrides: list | None = None,
    ) -> None: ...

class GraphOptions:
    mode: str | SchemaMode
    edge_mode: str | EdgeMode
    storage: RocksOptions
    index: IndexOptions
    def __init__(
        self,
        *,
        mode: str | SchemaMode = "auto",
        edge_mode: str | EdgeMode = "single",
        storage: RocksOptions | None = None,
        index: IndexOptions | None = None,
    ) -> None: ...

class P:
    tag: int
    value: Any
    def __init__(self, tag: int, value: Any) -> None: ...
    def __iter__(self): ...
    @staticmethod
    def eq(value: Any) -> P: ...
    @staticmethod
    def neq(value: Any) -> P: ...
    @staticmethod
    def gt(value: Any) -> P: ...
    @staticmethod
    def gte(value: Any) -> P: ...
    @staticmethod
    def lt(value: Any) -> P: ...
    @staticmethod
    def lte(value: Any) -> P: ...
    @staticmethod
    def between(v1: Any, v2: Any) -> P: ...
    @staticmethod
    def within(*values: Any) -> P: ...
    @staticmethod
    def without(*values: Any) -> P: ...

class __:
    @staticmethod
    def V(*ids: int) -> Traversal: ...
    @staticmethod
    def out(*labels: str) -> Traversal: ...
    @staticmethod
    def in_(*labels: str) -> Traversal: ...
    @staticmethod
    def both(*labels: str) -> Traversal: ...
    @staticmethod
    def outE(*labels: str) -> Traversal: ...
    @staticmethod
    def inE(*labels: str) -> Traversal: ...
    @staticmethod
    def bothE(*labels: str) -> Traversal: ...
    @staticmethod
    def outV() -> Traversal: ...
    @staticmethod
    def inV() -> Traversal: ...
    @staticmethod
    def otherV() -> Traversal: ...
    @staticmethod
    def has(*args: Any) -> Traversal: ...
    @staticmethod
    def hasLabel(*labels: str) -> Traversal: ...
    @staticmethod
    def values(*keys: str) -> Traversal: ...
    @staticmethod
    def properties(*keys: str) -> Traversal: ...
    @staticmethod
    def id() -> Traversal: ...
    @staticmethod
    def label() -> Traversal: ...
    @staticmethod
    def identity() -> Traversal: ...
    @staticmethod
    def constant(value: Any) -> Traversal: ...
    @staticmethod
    def limit(limit: int) -> Traversal: ...
    @staticmethod
    def count() -> Traversal: ...
    @staticmethod
    def dedup() -> Traversal: ...
    @staticmethod
    def degree(direction: str | Direction | None = None) -> Traversal: ...
    @staticmethod
    def fold() -> Traversal: ...
    @staticmethod
    def unfold() -> Traversal: ...
    @staticmethod
    def sum() -> Traversal: ...
    @staticmethod
    def max() -> Traversal: ...
    @staticmethod
    def min() -> Traversal: ...
    @staticmethod
    def mean() -> Traversal: ...
    @staticmethod
    def group() -> Traversal: ...
    @staticmethod
    def groupCount() -> Traversal: ...
    @staticmethod
    def path() -> Traversal: ...
    @staticmethod
    def simplePath() -> Traversal: ...
    @staticmethod
    def cyclicPath() -> Traversal: ...
    @staticmethod
    def as_(*labels: str) -> Traversal: ...
    @staticmethod
    def select(*labels: str) -> Traversal: ...
    @staticmethod
    def coalesce(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def union(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def and_(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def or_(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def not_(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def where(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def local(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def choose(predicate_t: Traversal, true_t: Traversal, false_t: Traversal | None = None) -> Traversal: ...
    @staticmethod
    def repeat(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def addV(label: str, vid: int | None = None) -> Traversal: ...
    @staticmethod
    def addE(label: str) -> Traversal: ...
    @staticmethod
    def from_(v: Any) -> Traversal: ...
    @staticmethod
    def to(v: Any) -> Traversal: ...
    @staticmethod
    def property(key: str, value: Any) -> Traversal: ...
    @staticmethod
    def nearest(property: str, query: Any, k: int) -> Traversal: ...
    @staticmethod
    def similarity(property: str, query: Any, metric: str | DistanceMetric) -> Traversal: ...
    @staticmethod
    def neighbors(
        source_prop: str, target_prop: str, k: int, entity_type: str | VectorEntityType
    ) -> Traversal: ...
    @staticmethod
    def hasId(value: Any) -> Traversal: ...
    @staticmethod
    def drop() -> Traversal: ...

class Traversal:
    steps: list  # internal: list of (opcode, args) tuples
    session: Any  # internal: ReadSession or TxSession or None

    def __init__(self, session: Any = None, steps: list | None = None) -> None: ...
    def V(self, *ids: int) -> Traversal: ...
    def E(self, *keys: str) -> Traversal: ...
    def addV(self, label: str, vid: int | None = None) -> Traversal: ...
    def addE(self, label: str) -> Traversal: ...
    def from_(self, v: Any) -> Traversal: ...
    def to(self, v: Any) -> Traversal: ...
    def property(self, key: str, value: Any) -> Traversal: ...
    def withProperties(self, *keys: str) -> Traversal: ...
    def out(self, *labels: str) -> Traversal: ...
    def in_(self, *labels: str) -> Traversal: ...
    def both(self, *labels: str) -> Traversal: ...
    def outE(self, *labels: str) -> Traversal: ...
    def inE(self, *labels: str) -> Traversal: ...
    def bothE(self, *labels: str) -> Traversal: ...
    def outV() -> Traversal: ...
    def inV() -> Traversal: ...
    def otherV() -> Traversal: ...
    def has(self, *args: Any) -> Traversal: ...
    def hasLabel(self, *labels: str) -> Traversal: ...
    def hasId(self, value: Any) -> Traversal: ...
    def hasRank(self, value: Any) -> Traversal: ...
    def values(self, *keys: str) -> Traversal: ...
    def properties(self, *keys: str) -> Traversal: ...
    def nearest(self, property: str, query: Any, k: int) -> Traversal: ...
    def with_ef_search(self, ef: int) -> Traversal: ...
    def with_metric(self, metric: str | DistanceMetric) -> Traversal: ...
    def similarity(self, property: str, query: Any, metric: str | DistanceMetric) -> Traversal: ...
    def neighbors(
        self, source_prop: str, target_prop: str, k: int, entity_type: str | VectorEntityType
    ) -> Traversal: ...
    def id(self) -> Traversal: ...
    def label(self) -> Traversal: ...
    def rank(self) -> Traversal: ...
    def identity(self) -> Traversal: ...
    def constant(self, value: Any) -> Traversal: ...
    def limit(self, limit: int) -> Traversal: ...
    def range(self, lo: int, hi: int) -> Traversal: ...
    def skip(self, n: int) -> Traversal: ...
    def tail(self, n: int) -> Traversal: ...
    def count(self) -> Traversal: ...
    def dedup(self) -> Traversal: ...
    def degree(self, direction: str | Direction | None = None) -> Traversal: ...
    def fold(self) -> Traversal: ...
    def unfold(self) -> Traversal: ...
    def sum(self) -> Traversal: ...
    def max(self) -> Traversal: ...
    def min(self) -> Traversal: ...
    def mean(self) -> Traversal: ...
    def group(self) -> Traversal: ...
    def groupCount(self) -> Traversal: ...
    def order(self) -> Traversal: ...
    def by(self, key_spec: Any = None, order: str | Order = ...) -> Traversal: ...
    def path(self) -> Traversal: ...
    def simplePath(self) -> Traversal: ...
    def cyclicPath(self) -> Traversal: ...
    def as_(self, *labels: str) -> Traversal: ...
    def select(self, *labels: str) -> Traversal: ...
    def coalesce(self, *traversals: Traversal) -> Traversal: ...
    def union(self, *traversals: Traversal) -> Traversal: ...
    def and_(self, *traversals: Traversal) -> Traversal: ...
    def or_(self, *traversals: Traversal) -> Traversal: ...
    def not_(self, traversal: Traversal) -> Traversal: ...
    def where(self, traversal: Traversal) -> Traversal: ...
    def local(self, traversal: Traversal) -> Traversal: ...
    def choose(self, predicate_t: Traversal, true_t: Traversal, false_t: Traversal | None = None) -> Traversal: ...
    def repeat(self, traversal: Traversal) -> Traversal: ...
    def until(self, traversal: Traversal) -> Traversal: ...
    def times(self, n: int) -> Traversal: ...
    def emit(self, traversal: Traversal | None = None) -> Traversal: ...
    def drop(self) -> Traversal: ...
    def next(self) -> Any: ...
    def to_list(self) -> list: ...
    def toList(self) -> list: ...
    def to_set(self) -> set: ...
    def toSet(self) -> set: ...
    def iterate(self) -> None: ...
    def explain(self) -> str: ...

class GraphTraversal(Traversal): ...

class IndexManager:
    def rebuild(self, entity_type: str | VectorEntityType, property: str) -> None: ...
    def save(self, entity_type: str | VectorEntityType, property: str) -> None: ...
    def save_all(self) -> None: ...

class Graph:
    def __init__(self, path: str, *, options: GraphOptions | None = None) -> None: ...
    @staticmethod
    def open_with_options(path: str, *, options: GraphOptions | None = None) -> Graph: ...
    def read(self) -> ReadSession: ...
    def begin(self) -> TxSession: ...
    def open_schema(self) -> SchemaSession: ...
    def open_bulk_loader(self) -> BulkLoader: ...
    def index_manager(self) -> IndexManager: ...
    def close(self) -> None: ...

class SchemaSession:
    def add_vertex_label(self, name: str) -> SchemaSession: ...
    def add_edge_label(self, name: str) -> SchemaSession: ...
    def add_property_key(self, name: str, data_type: int | DataType) -> SchemaSession: ...
    def set_edge_mode(self, mode: str | EdgeMode) -> SchemaSession: ...
    def set_schema_mode(self, mode: str | SchemaMode) -> SchemaSession: ...
    def add_vector_index(
        self,
        config: VectorIndexConfig | None = None,
        *,
        entity_type: str | VectorEntityType = ...,
        property: str | None = None,
        dimension: int | None = None,
        metric: str | DistanceMetric = ...,
        algorithm: str | AnnAlgorithm = ...,
        m: int = 16,
        ef_construction: int = 200,
        ef_search: int = 50,
        quantization: str | Quantization = ...,
    ) -> SchemaSession: ...
    def drop_vector_index(self, entity_type: str | VectorEntityType, property: str) -> SchemaSession: ...
    def commit(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool | None: ...

class BulkLoader:
    def with_work_dir(self, path: str) -> BulkLoader: ...
    def with_max_sst_size(self, bytes: int) -> BulkLoader: ...
    def with_max_memory(self, bytes: int) -> BulkLoader: ...
    def load_vertices(self, vertices: list[BulkVertex | dict]) -> BulkLoader: ...
    def load_edges(self, edges: list[BulkEdge | dict]) -> BulkLoader: ...
    def commit(self) -> BulkLoadStats: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool | None: ...

class ReadSession:
    def g(self) -> GraphTraversal: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool | None: ...

class TxSession:
    def g(self) -> GraphTraversal: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool | None: ...

class Vertex:
    def __init__(self, d: dict) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self): ...
    @property
    def id(self) -> int: ...
    @property
    def label(self) -> str: ...
    @property
    def properties(self) -> dict: ...

class Edge:
    def __init__(self, d: dict) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self): ...
    @property
    def src(self) -> int: ...
    @property
    def dst(self) -> int: ...
    @property
    def label(self) -> str: ...
    @property
    def rank(self) -> int: ...
    @property
    def properties(self) -> dict: ...

class Property:
    def __init__(self, d: dict) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> Any: ...

class Int32:
    value: int
    def __init__(self, value: int) -> None: ...

class Int64:
    value: int
    def __init__(self, value: int) -> None: ...

class UInt16:
    value: int
    def __init__(self, value: int) -> None: ...

class Float32:
    value: float
    def __init__(self, value: float) -> None: ...

class Float64:
    value: float
    def __init__(self, value: float) -> None: ...

class Uuid:
    value: str
    def __init__(self, value: str) -> None: ...

class Vector:
    values: list[float]
    def __init__(self, values: Any) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def tolist(self) -> list[float]: ...
    def numpy(self) -> Any: ...
