"""Type stubs for rocksgraph — enables IDE autocompletion and suppresses Pylance warnings."""
from __future__ import annotations
from typing import Any, Optional, List, Set
from enum import Enum

class T:
    id: str
    label: str
    key: str
    value: str

class Direction(Enum):
    OUT = "out"
    IN = "in"
    BOTH = None

class Order(Enum):
    asc = "asc"
    desc = "desc"

class P:
    tag: int
    value: Any
    def __init__(self, tag: int, value: Any) -> None: ...
    def __iter__(self): ...
    @staticmethod
    def eq(value: Any) -> P: ...
    @staticmethod
    def neq(value: Any) -> P: ...
    @staticmethod
    def gt(value: Any) -> P: ...
    @staticmethod
    def gte(value: Any) -> P: ...
    @staticmethod
    def lt(value: Any) -> P: ...
    @staticmethod
    def lte(value: Any) -> P: ...
    @staticmethod
    def between(v1: Any, v2: Any) -> P: ...
    @staticmethod
    def within(*values: Any) -> P: ...
    @staticmethod
    def without(*values: Any) -> P: ...

class __:
    @staticmethod
    def V(*ids: int) -> Traversal: ...
    @staticmethod
    def out(*labels: str) -> Traversal: ...
    @staticmethod
    def in_(*labels: str) -> Traversal: ...
    @staticmethod
    def both(*labels: str) -> Traversal: ...
    @staticmethod
    def outE(*labels: str) -> Traversal: ...
    @staticmethod
    def inE(*labels: str) -> Traversal: ...
    @staticmethod
    def bothE(*labels: str) -> Traversal: ...
    @staticmethod
    def outV() -> Traversal: ...
    @staticmethod
    def inV() -> Traversal: ...
    @staticmethod
    def otherV() -> Traversal: ...
    @staticmethod
    def has(*args: Any) -> Traversal: ...
    @staticmethod
    def hasLabel(*labels: str) -> Traversal: ...
    @staticmethod
    def values(*keys: str) -> Traversal: ...
    @staticmethod
    def properties(*keys: str) -> Traversal: ...
    @staticmethod
    def id() -> Traversal: ...
    @staticmethod
    def label() -> Traversal: ...
    @staticmethod
    def identity() -> Traversal: ...
    @staticmethod
    def constant(value: Any) -> Traversal: ...
    @staticmethod
    def limit(limit: int) -> Traversal: ...
    @staticmethod
    def count() -> Traversal: ...
    @staticmethod
    def dedup() -> Traversal: ...
    @staticmethod
    def degree(direction: Optional[str] = None) -> Traversal: ...
    @staticmethod
    def fold() -> Traversal: ...
    @staticmethod
    def unfold() -> Traversal: ...
    @staticmethod
    def sum() -> Traversal: ...
    @staticmethod
    def max() -> Traversal: ...
    @staticmethod
    def min() -> Traversal: ...
    @staticmethod
    def mean() -> Traversal: ...
    @staticmethod
    def group() -> Traversal: ...
    @staticmethod
    def groupCount() -> Traversal: ...
    @staticmethod
    def path() -> Traversal: ...
    @staticmethod
    def simplePath() -> Traversal: ...
    @staticmethod
    def cyclicPath() -> Traversal: ...
    @staticmethod
    def as_(*labels: str) -> Traversal: ...
    @staticmethod
    def select(*labels: str) -> Traversal: ...
    @staticmethod
    def coalesce(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def union(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def and_(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def or_(*traversals: Traversal) -> Traversal: ...
    @staticmethod
    def not_(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def where(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def local(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def choose(predicate_t: Traversal, true_t: Traversal, false_t: Optional[Traversal] = None) -> Traversal: ...
    @staticmethod
    def repeat(traversal: Traversal) -> Traversal: ...
    @staticmethod
    def addV(label: str, vid: Optional[int] = None) -> Traversal: ...
    @staticmethod
    def addE(label: str) -> Traversal: ...
    @staticmethod
    def from_(v: Any) -> Traversal: ...
    @staticmethod
    def to(v: Any) -> Traversal: ...
    @staticmethod
    def property(key: str, value: Any) -> Traversal: ...
    @staticmethod
    def hasId(value: Any) -> Traversal: ...
    @staticmethod
    def drop() -> Traversal: ...

class Traversal:
    steps: list  # internal: list of (opcode, args) tuples
    session: Any  # internal: ReadSession or TxSession or None

    def __init__(self, session: Any = None, steps: Optional[list] = None) -> None: ...
    def V(self, *ids: int) -> Traversal: ...
    def E(self, *keys: str) -> Traversal: ...
    def addV(self, label: str, vid: Optional[int] = None) -> Traversal: ...
    def addE(self, label: str) -> Traversal: ...
    def from_(self, v: Any) -> Traversal: ...
    def to(self, v: Any) -> Traversal: ...
    def property(self, key: str, value: Any) -> Traversal: ...
    def withProperties(self, *keys: str) -> Traversal: ...
    def out(self, *labels: str) -> Traversal: ...
    def in_(self, *labels: str) -> Traversal: ...
    def both(self, *labels: str) -> Traversal: ...
    def outE(self, *labels: str) -> Traversal: ...
    def inE(self, *labels: str) -> Traversal: ...
    def bothE(self, *labels: str) -> Traversal: ...
    def outV(self) -> Traversal: ...
    def inV(self) -> Traversal: ...
    def otherV(self) -> Traversal: ...
    def has(self, *args: Any) -> Traversal: ...
    def hasLabel(self, *labels: str) -> Traversal: ...
    def hasId(self, value: Any) -> Traversal: ...
    def hasRank(self, value: Any) -> Traversal: ...
    def values(self, *keys: str) -> Traversal: ...
    def properties(self, *keys: str) -> Traversal: ...
    def id(self) -> Traversal: ...
    def label(self) -> Traversal: ...
    def rank(self) -> Traversal: ...
    def identity(self) -> Traversal: ...
    def constant(self, value: Any) -> Traversal: ...
    def limit(self, limit: int) -> Traversal: ...
    def range(self, lo: int, hi: int) -> Traversal: ...
    def skip(self, n: int) -> Traversal: ...
    def tail(self, n: int) -> Traversal: ...
    def count(self) -> Traversal: ...
    def dedup(self) -> Traversal: ...
    def degree(self, direction: Optional[str] = None) -> Traversal: ...
    def fold(self) -> Traversal: ...
    def unfold(self) -> Traversal: ...
    def sum(self) -> Traversal: ...
    def max(self) -> Traversal: ...
    def min(self) -> Traversal: ...
    def mean(self) -> Traversal: ...
    def group(self) -> Traversal: ...
    def groupCount(self) -> Traversal: ...
    def order(self) -> Traversal: ...
    def by(self, key_spec: Any, order: str = "asc") -> Traversal: ...
    def path(self) -> Traversal: ...
    def simplePath(self) -> Traversal: ...
    def cyclicPath(self) -> Traversal: ...
    def as_(self, *labels: str) -> Traversal: ...
    def select(self, *labels: str) -> Traversal: ...
    def coalesce(self, *traversals: Traversal) -> Traversal: ...
    def union(self, *traversals: Traversal) -> Traversal: ...
    def and_(self, *traversals: Traversal) -> Traversal: ...
    def or_(self, *traversals: Traversal) -> Traversal: ...
    def not_(self, traversal: Traversal) -> Traversal: ...
    def where(self, traversal: Traversal) -> Traversal: ...
    def local(self, traversal: Traversal) -> Traversal: ...
    def choose(self, predicate_t: Traversal, true_t: Traversal, false_t: Optional[Traversal] = None) -> Traversal: ...
    def repeat(self, traversal: Traversal) -> Traversal: ...
    def until(self, traversal: Traversal) -> Traversal: ...
    def times(self, n: int) -> Traversal: ...
    def emit(self, traversal: Optional[Traversal] = None) -> Traversal: ...
    def drop(self) -> Traversal: ...
    def next(self) -> Any: ...
    def to_list(self) -> list: ...
    def toList(self) -> list: ...
    def to_set(self) -> Set: ...
    def toSet(self) -> Set: ...
    def iterate(self) -> None: ...

class GraphTraversal(Traversal): ...

class Graph:
    def __init__(self, path: str) -> None: ...
    def read(self) -> ReadSession: ...
    def tx(self) -> TxSession: ...

class ReadSession:
    def traversal(self) -> GraphTraversal: ...

class TxSession:
    def traversal(self) -> GraphTraversal: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> TxSession: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class Vertex:
    def __init__(self, d: dict) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self): ...
    @property
    def id(self) -> int: ...
    @property
    def label(self) -> str: ...
    @property
    def properties(self) -> dict: ...

class Edge:
    def __init__(self, d: dict) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self): ...
    @property
    def src(self) -> int: ...
    @property
    def dst(self) -> int: ...
    @property
    def label(self) -> str: ...
    @property
    def rank(self) -> int: ...
    @property
    def properties(self) -> dict: ...


class Property:
    def __init__(self, d: dict) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __repr__(self) -> str: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> Any: ...

class Int32:
    value: int
    def __init__(self, value: int) -> None: ...

class Int64:
    value: int
    def __init__(self, value: int) -> None: ...

class UInt16:
    value: int
    def __init__(self, value: int) -> None: ...

class Float32:
    value: float
    def __init__(self, value: float) -> None: ...

class Float64:
    value: float
    def __init__(self, value: float) -> None: ...

class Uuid:
    value: str
    def __init__(self, value: str) -> None: ...
