[package]
name = "rocksgraph-python"
version = "0.1.1"
edition = "2021"
authors = ["Austin Han <austinhan1024@gmail.com>"]
license = "MIT OR Apache-2.0"
publish = false

[lib]
name = "_rocksgraph"
crate-type = ["cdylib"]

[dependencies]
rocksgraph = { version = "0.1.1", path = "../../rocksgraph" }
pyo3 = { version = "0.21.2", features = ["extension-module"] }
