[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "rocksgraph"
version = "0.1.1"
description = "Embedded property graph database with Gremlin-style traversals."
authors = [{ name = "Austin Han", email = "austinhan1024@gmail.com" }]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "_rocksgraph"
